### ISSUE TITLE
Can I directly use log_m_ratio matrix to do methylation differential analysis?

### ISSUE THREAD

**Issue by YingziZhang-github** [Shians/NanoMethViz#28]
Hi Shian,

Following the guideline in R help, I used the conversion function `bsseq_to_log_methy_ratio` to convert from my BSseq object `bsseq` to a matrix of log-methylation ratios `log_m_ratio`. I understand that the `log_m_ratio` matrix can be used with the `plotMDS` or `plotPCA` function.

If I want to do differential methylation analysis and to distinguish **differential methylated loci** and **loci without significant methylation level changes** _within one sample_ and _in different treatment conditions_. Can I directly use the values in `log_m_ratio` matrix? Do you have suggestions what statistical method should I use?

Thank you very much for your time. Looking forward to your reply!

Yingzi

**Comment by Shians** [comment]
The methylation ratios shouldn't be used for differential methylation analysis, because the ratios don't capture the coverage which is important for statistical methods. For example we are more confident about a loci that has 0.5 methylation if we captured 50 methylated CG and 50 unmethylated CG rather than 1 and 1. I recommend using the `BSSeq` object directly with DSS or bsseq. I believe DSS can work when there are no replicates within conditions, not sure about bsseq.

**Comment by YingziZhang-github** [comment]
Hi Shian,

Thank you for the explanation. I am moving on with DSS instructions for further differential  analysis. Many thanks.

Yingzi
